name: Generate Snake Game

permissions:
  contents: write

on:
  schedule:
    # Runs every 12 hours
    - cron: "0 */12 * * *"
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          # Adding these options to make the snake eat your contributions
          svg_out_path: dist/github-contribution-grid-snake.svg
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            dist/github-contribution-grid-snake.gif
          snake_color: 'purple'
          # Adding the contribution grid settings
          color_snake: "purple"
          color_dots: "#DDD,#579E43,#579E43,#579E43,#216E39"

      - uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
