name: Generate Snake Contribution Grid

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake animation
        uses: Platane/snk@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist

      - name: Push Snake animation to the output branch
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: output
          build_dir: dist

  deploy:
    runs-on: ubuntu-latest
    needs: generate

    steps:
      - name: Deploy Snake animation
        run: |
          mkdir -p public
          cp dist/snake.svg public/snake.svg
