name: Generate Snake

# Controls when the action will run
on:
  schedule:
      # every 12 hours
    - cron: "0 */12 * * *"
  
  # This command allows us to run the Action automatically from the Actions tab.
  workflow_dispatch:

# The sequence of runs in this workflow:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks repo under $GITHUB_WORKSHOP, so your job can access it
      - uses: actions/checkout@v2

      # Generates the snake  
      - uses: Platane/snk@v3
        with:
          # your GitHub username
          github_user_name: ${{ github.repository_owner }}
          # generates a snake game board using GitHub's contribution graph 
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Push the changes
      - name: Push to output branch
        uses: EndBug/add-and-commit@v7
        with:
          branch: output
          message: 'Generate Contribution Snake'
          add: 'dist'
